version: '3.1'

services:

  mongo:
    image: mongo
    restart: never
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: adminPass
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017